name: "🐞 Bug Report"
description: "Report a reproducible bug with clear steps"
title: "bug: <short-description>"
labels: ["bug", "needs triage"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the bug clearly."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Numbered steps to reproduce the issue. Try using online environments, e.g. Codespaces, shared environment, shared problem."
      placeholder: "1. Go to...\n2. Click...\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "OS, Browser, App version, Codespaces/Jules"
      placeholder: "Fedora 41, Firefox 120, v1.2.3"
    validations:
      required: true
