name: Pull Request Template
body: |
  ## Summary
  
  <!-- Describe what this PR does -->

  ## Related Issue
  
  Closes #<issue-number>

  ## Checklist
  
  - [ ] Issue linked and closing syntax used
  - [ ] Tests added / updated
  - [ ] Documentation updated
